### ISSUE TITLE
[FEAT] Alpine base image

### ISSUE THREAD

**Issue by lizardfish0** [linuxserver/docker-ffmpeg#38]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Provide a version of this container built on linuxserver/docker-baseimage-alpine.

### Reason for change

I use a few containers in my setup which make use of the linuxserver sonarr and radarr images with binaries/libraries from this ffmpeg image layered on top of them (see [mdhiggins/sonarr-sma](https://github.com/mdhiggins/sonarr-sma)). This works great for sonarr, which current has its master branch based on ubuntu 22.04 and its development branch on alpine, but not for radarr which uses alpine for both.

If the long term plan is to use alpine for linuxserver's sonarr/radarr images, a version of this container built on that base would be useful!

I'm happy to put a branch together and submit a PR if you're willing to take a look.

**Comment by Roxedus** [comment]
I'm struggling to see how the base image of sonarr is related to the usage if this image.

**Comment by lizardfish0** [comment]
If I want to use the compiled binaries and libraries from this image in another, it's much easier if they share an operating system.

**Comment by Roxedus** [comment]
The compiled binaries from the bin branch is only intended for this containers main branch.

**Comment by lizardfish0** [comment]
I know, apologies, I'm very aware of the jankyness of this approach.

Generally, my problem is that there are only two quality sources of pre-compiled `ffmpeg` binaries. There's [johnvansickle](https://johnvansickle.com/ffmpeg/)'s (which don't include hardware acceleration libs), or just installing whatever is in repo. The latter is usually outdated and has only included VAAPI (if anything for hwaccel) in the past.

I've been using the second approach but I'd really prefer a solution that allows me to use cuda/nvenc/nvdec. The repo version of ffmpeg (or any ffmpeg < 4.5 I believe) is broken for encoding HEVC with `vaapi`, which is annoying.

That leaves me with really two options. I can compile my own within the container which takes time, maintenance, and reduces the "just a docker compose entry"-ness of my stack, or (what we've changed the repo I linked to do), I can grab what I need from one of the popular `ffmpeg` images. From what I've found my options there were `jrottenberg/ffmpeg` and this repository, with this being a more attractive option considering it shares a maintainer with the sonarr image.

I know this is a very dirty way of going about this. If you have any suggestions I'm all ears and would appreciate it, but an alpine-based image really would be a help.

**Comment by aptalca** [comment]
I did the recent upgrade of this image to v6, and honestly, this image is just meant to be a self contained ffmpeg instance with the kitchen sink included in terms of enabled libraries and features. I put zero effort into trying to compile a static binary. I even took a bunch of shortcuts including directly copying select libs from the build stage to the final image instead of installing the libs from the repo (which often come with a bunch of other packages as deps that are not necessary in this image).

There are tons of shared libs, and most depend on glibc. But that's ok, because all we care about is making sure all those libs are in the final image/container.

Since alpine is musl based, this won't be compatible with alpine based containers even if you copy the libs over as well as the binary. Sonarr is alpine based, so that's a no go.

Switching this image to Alpine is a no go because of lack of support for various hw acceleration libs on alpine (no nvidia docker for starters).

Johnvansickle provides probably the most popular static build of ffmpeg out there but it's missing some hw acceleration due to those not supporting static builds.

I'm not familiar with the other one you mentioned.

But your best bet is using ffmpeg from the alpine repo. If you need things that the repo version doesn't support, you'll probably have to compile it yourself. You can also PR additions to the alpine repo version on their gitlab. They're very friendly towards PRs.

And I just noticed you said your motivation was you wanted cuda. Unfortunately that's a no go as there is no nvidia docker for Alpine.

**Comment by lizardfish0** [comment]
Appreciate the information! Was not aware of the lack of alpine support in nvidia-docker. [Maybe someday](https://github.com/NVIDIA/nvidia-docker/issues/1606).
